name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  # CI builds don't benefit very much from this.
  CARGO_INCREMENTAL: 0

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
  
      - name: Check formatting
        run: cargo fmt --check

  check:
    name: Clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
  
      - name: Check code
        run: cargo clippy
